research_task:
  description: >
    Research and find the best hotel offers available in {city}. Gather up-to-date information on prices, amenities, locations, and special deals for travelers.
  expected_output: >
    A list of 10 bullet points highlighting the most relevant hotel offers, including hotel names, prices, amenities, and any special deals in {city}.
  agent: travel_agent

reporting_task:
  description: >
    Analyze the research findings and select the 3 best hotel offers based on relevance, value, and user needs. Clearly present these options to the user, including hotel names, prices, amenities, and reasons for selection.
  expected_output: >
    A markdown-formatted summary listing the top 3 hotel offers, each with a brief explanation of why it was chosen, including hotel name, price, amenities, and any special deals.
  agent: reporting_analyst