research_task:
  name: "Research Hotels in {{city}}"
  description: "Find and list exactly 10 hotels in {{city}} that are available for booking from {{start_date}} to {{end_date}} for {{people}} people."
  agent: "travel_agent"
  prompt_template: |
    Your task is to find exactly 10 hotels in {{city}} that are available for booking from {{start_date}} to {{end_date}} for {{people}} people.
    Only include hotels that have availability for the full date range.
    For each hotel, provide:
    - Name of the hotel
    - A brief description focusing on amenities and location
    - Available pricing or price range for the specified dates
    - Direct booking or reservation link with preselected dates and number of people.
    Use the Serper search tool to gather the latest and most relevant information from reputable booking sites.
    Respond ONLY with a JSON object like this:

    {
      "hotels": [
        {
          "name": "Hotel Example",
          "description": "A nice hotel located downtown with free WiFi.",
          "price_range": "$100-$150 per night",
          "booking_link": "https://example.com/hotel-booking"
        }
      ]
    }
  expected_output: |
    A JSON object containing exactly 10 hotels with all requested details.

reporting_task:
  name: "Reporting"
  description: "Summarize and filter the top hotels in {{city}} for the period {{start_date}} to {{end_date}} for {{people}} people."
  agent: "reporting_analyst"
  prompt_template: |
    Based on the travel agent’s research for {{city}} from {{start_date}} to {{end_date}} for {{people}} people, select the 5 best hotels considering:
    - Price and overall value
    - Location and amenities
    - User reviews and ratings
    - Confirmed availability for the entire period
    Then, provide:
    - A summary paragraph highlighting why these hotels are the best choices
    - The full JSON list of the selected 5 hotels

    Please respond ONLY with a JSON object in this format:

    {
      "summary": "A clear paragraph summarizing the best hotel options in {{city}} for {{start_date}} to {{end_date}} for {{people}} people",
      "hotels": [
        {
          "name": "Hotel Example",
          "description": "A nice hotel located downtown with free WiFi.",
          "price_range": "$100-$150 per night",
          "booking_link": "https://example.com/hotel-booking"
        }
      ]
    }
  expected_output: |
    A JSON object with a "summary" string and exactly 5 hotels selected from the research results with direct booking link with preselected dates and number of people.
